#!/bin/zsh

echo "🚀 Welcome to the aronmoles/dotfiles installer!"
echo "-------------------------------------------------"
echo
export DOTFILES_PATH="$HOME/.dotfiles"
echo "👉  Cloning into: '$DOTFILES_PATH'"

# To test that git is installed (if not macOS will prompt an installer)
git --version

#git clone --depth 1 git@github.com:aronmoles/dotfiles.git "$DOTFILES_PATH"
export DOTFILES_PATH="$HOME/dotfiles"

sh "$DOTFILES_PATH/bin/install.sh"
