version: "3.8"

services:

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    env_file:
      - "${DOTFILES_PATH}/.conf/.mongodb"
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 7001:8081
    env_file:
      - "${DOTFILES_PATH}/.conf/.mongo-express"
    restart: unless-stopped

volumes:
  mongodb:
    driver: local

