#!/bin/zsh

set -euo pipefail
source "$DOTFILES_PATH/scripts/functions/_index.sh"

BREW_DIR="$DOTFILES_PATH/brew"
BREW_PATH="$BREW_DIR/Brewfile"

mkdir -p "$BREW_DIR"
brew bundle install -f --file "$BREW_PATH"

log::done
