#!/usr/bin/env bash

set -euo pipefail
source "$DOTFILES_PATH/scripts/functions/_index.sh"

args::check_exists "$1" "Invalid process name"

ps aux | grep $1 | grep -v grep | grep -v kill-named | awk '{print $2}' | xargs kill -9

log::done
