#!/bin/zsh

source "$DOTFILES_PATH/scripts/functions/_index.sh"

DATABASE_NAME=$1
SQL_FILE=$2

args::checkExists "$DATABASE_NAME" "Database name is not defined"
args::checkExists "$SQL_FILE" "SQL File is not defined"

docker exec -i mysql mysql -u root --password=cuatroochenta "$DATABASE_NAME" < "$SQL_FILE"
