#!/bin/zsh

source "$DOTFILES_PATH/scripts/functions/_index.sh"

args::check_exists "$1" "text to hash not defined"

TOKEN=$(echo -n "$1" | openssl dgst -sha256)
echo -n $TOKEN | pbcopy
echo "$TOKEN"

osascript -e 'display notification "'"$TOKEN"'" with title "SHA256 copied to the clipboard"'
